# import Sensor Superclass
import sensor

# import abstract class libraries (ABC = abstact parent class, abstractmethod = method decorator)
from abc import ABC, abstractmethod

class pressureSensor(sensor.sensor):
    def __init__(self, sensorAddress, gpio):
    	# variable are hidden for security reasons
        self._sensorType = "PRES"
        # sensor Addresss, random alphanumaric address generated by Station 
        self._sensorAddress = sensorAddress
        self._gpio = gpio

    # variable accessors and mutators. 
    @property
    def sensorType(self):
    	return self._sensorType

    @sensorType.setter
    def sensorType(self, sensorType):
        self._sensorType = sensorType
    
    @property
    def sensorAddress(self):
    	return self._sensorAddress
    
    @sensorAddress.setter
    def sensorAddress(self, sensorAddress):
        self._sensorAddress = sensorAddress

    @property
    def gpio(self):
    	return self._gpio
    
    @gpio.setter
    def gpio(self, gpio):
        self._gpio = gpio

    # returns measurement
    def getMeasurement(self):
        # implement correct code: return integer value 12 for now
        return 12

    def __str__(self):
        return "Type: " + self._sensorType + "\nAddress: " + self._sensorAddress + "\nGPIO: " + str(self._gpio)